=== kmedina47/assignment-1--principles-of-databases--cs-365--fall-2025/xml/student.dtd
<!-- =====================================================================================================
  The root element: students

  The students container (root) element must contain one or more student elements. This is represented by the + metacharacter. One is required, but there is no limit to how many are allowed.

  Note: This element may not contain parsed character data (PCDATA) that includes entities, or simple character data (CDATA).
  ==================================================================================================== -->
<!ELEMENT student-directory (student)+>

<!-- =====================================================================================================
  The student container element must contain all specified elements. The middle-name and preferred-name elements have the ? metacharacter, representing that each may appear zero or one time.
  ==================================================================================================== -->
<!ELEMENT student (first-name, middle-name?, last-name, preferred-name?, email, phone, academic-status, gpa, major, minor, enrollment-status, advisor, initial-enrollment-date, graduation-date)>

<!-- =====================================================================================================
  All elements contained in student are defined here.
  ==================================================================================================== -->
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT middle-name (#PCDATA)>
<!ELEMENT last-name (#PCDATA)>
<!ELEMENT preferred-name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT academic-status (#PCDATA)>
<!ELEMENT gpa (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT enrollment-status (#PCDATA)>
<!ELEMENT advisor (#PCDATA)>
<!ELEMENT initial-enrollment-date (#PCDATA)>
<!ELEMENT graduation-date (#PCDATA)>

<!ATTLIST student
          studentID CDATA #REQUIRED>

=== kmedina47/assignment-1--principles-of-databases--cs-365--fall-2025/xml/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE student-directory SYSTEM "student.dtd">

<student-directory>
  <student studentID="1234567">
    <first-name>Gordon</first-name>
    <middle-name>Matthew</middle-name>
    <last-name>Sumner</last-name>
    <preferred-name>Sting</preferred-name>
    <email>sting@thepolice.com</email>
    <phone>212.123.4567</phone>
    <academic-status>first year</academic-status>
    <gpa>4.0</gpa>
    <major>Music</major>
    <minor>English</minor>
    <enrollment-status>full-time</enrollment-status>
    <advisor>Andy Summers</advisor>
    <initial-enrollment-date>08-25-1969</initial-enrollment-date>
    <graduation-date>05-01-1973</graduation-date>
  </student>
  <student studentID="4567890">
    <first-name>Kim</first-name>
    <middle-name/>
    <last-name>Thayil</last-name>
    <preferred-name/>
    <email>kim@soundgarden.com</email>
    <phone>206.123.4567</phone>
    <academic-status>second year</academic-status>
    <gpa>3.0</gpa>
    <major>Philosophy</major>
    <minor>Music</minor>
    <enrollment-status>full-time</enrollment-status>
    <advisor>Chris Cornell</advisor>
    <initial-enrollment-date>08-25-1978</initial-enrollment-date>
    <graduation-date>05-01-1982</graduation-date>
  </student>
  <student studentID="8302438">
    <first-name>Saul</first-name>
    <middle-name/>
    <last-name>Hudson</last-name>
    <preferred-name>Slash</preferred-name>
    <email>slash@gnr.com</email>
    <phone>213.456.8392</phone>
    <academic-status>fourth year</academic-status>
    <gpa>2.0</gpa>
    <major>Music</major>
    <minor>Criminal Justice</minor>
    <enrollment-status>part-time</enrollment-status>
    <advisor>Axl Rose</advisor>
    <initial-enrollment-date>08-25-1983</initial-enrollment-date>
    <graduation-date>05-01-1987</graduation-date>
  </student>
  <student studentID="2983928">
    <first-name>Emily</first-name>
    <middle-name/>
    <last-name>Kokal</last-name>
    <preferred-name/>
    <email>emily@warpaint.com</email>
    <phone>213.123.7654</phone>
    <academic-status>third year</academic-status>
    <gpa>3.8</gpa>
    <major>Political Science</major>
    <minor>Law</minor>
    <enrollment-status>full-time</enrollment-status>
    <advisor>Jenny Lee Lindberg</advisor>
    <initial-enrollment-date>08-25-1998</initial-enrollment-date>
    <graduation-date>05-01-2002</graduation-date>
  </student>
  <student studentID="7645726">
    <first-name>Mike</first-name>
    <middle-name/>
    <last-name>Inez</last-name>
    <preferred-name/>
    <email>mike@aic.com</email>
    <phone>213.444.3323</phone>
    <academic-status>second year</academic-status>
    <gpa>4.0</gpa>
    <major>Business Management</major>
    <minor>Math</minor>
    <enrollment-status>full-time</enrollment-status>
    <advisor>Jerry Cantrell</advisor>
    <initial-enrollment-date>08-25-1984</initial-enrollment-date>
    <graduation-date>05-01-1988</graduation-date>
  </student>
</student-directory>
